" NOTE: for gvim settings see ~/.gvimrc

syntax on 

set shortmess+=I " don't give the intro message when starting Vim
set tabstop=2 shiftwidth=2
set nowrap
set autoindent
set autowrite
set hlsearch ignorecase
set ruler
set formatoptions=2croql
set equalalways splitright
set fillchars=vert:\ ,fold:\ 
set whichwrap=<,>,h,l,[,]
set mouse=a " enable the use of the mouse in the terminal
set pastetoggle=<F2>

set expandtab
autocmd BufRead Makefile set noexpandtab

set textwidth=120
autocmd FileType mail set textwidth=72
autocmd BufRead .git/COMMIT_EDITMSG set textwidth=72

set showmatch matchtime=3 " show the matched parenthesis for 0.3 seconds
highlight MatchParen ctermbg=white

" Folding
set foldcolumn=1
set foldmethod=manual
hi FoldColumn guifg=#333 guibg=#FFF

set number
highlight LineNr ctermfg=grey guifg=grey

set colorcolumn=+0
highlight ColorColumn ctermbg=lightgrey guibg=lightgrey
autocmd FileType nerdtree set colorcolumn=

" automatically reload the vimrc if its modified
autocmd BufWritePost .vimrc source %

" ,,Learning, the hard way''
" http://cloudhead.io/2010/04/24/staying-the-hell-out-of-insert-mode/
inoremap <Left>  <NOP>
inoremap <Right> <NOP>
inoremap <Up>    <NOP>
inoremap <Down>  <NOP>

" Move a line up with Alt-Up and move it down with Alt-Down
nnoremap <A-Up>        :m-2<CR>  ==
nnoremap <A-Down>      :m+ <CR>  ==
vnoremap <A-Up>        :m  -2<CR>gv= gv
vnoremap <A-Down>      :m'>+ <CR>gv= gv

" http://stevelosh.com/blog/2010/09/coming-home-to-vim/#using-the-leader
let mapleader=","

map <F12> :set spell!<cr>

" ----------------------------------------------------------
" plugins

" Pathogen
call pathogen#runtime_append_all_bundles()

" NerdTree
let NERDTreeIgnore=['\.class$', '\~$', '\.bak$']
nmap <silent> <c-t> :NERDTreeToggle<cr>
inoremap <c-t> <esc>:NERDTreeClose<cr>a

" Gundo
nnoremap <F5> :GundoToggle<CR>

" minibufexpl
let g:miniBufExplMapWindowNavVim = 1
let g:miniBufExplMapWindowNavArrows = 1
let g:miniBufExplMapCTabSwitchBufs = 1
let g:miniBufExplModSelTarget = 1

" lesscss
autocmd BufNewFile,BufRead *.less set filetype=less
